config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :shoppers
  resources :orders
  resources :merchants do
    resources :disbursements, only: :index
  end
  resources :disbursements, only: :index

  root 'merchants#index'
end

app/models/shopper.rb
class Shopper < ApplicationRecord
  has_many :orders, dependent: :destroy

  validates :name, :email, :nif, presence: true
  validates :name, :email, length: { maximum: 120 }
  # TODO: add CustomValidator < ActiveModel::Validator for email and nif formats
end

app/controllers/shoppers_controller.rb
class ShoppersController < ApplicationController
  before_action :set_shopper, only: [:show, :edit, :update, :destroy]

  # GET /shoppers
  # GET /shoppers.json
  def index
    @shoppers = Shopper.all
  end

  # GET /shoppers/1
  # GET /shoppers/1.json
  def show
  end

  # GET /shoppers/new
  def new
    @shopper = Shopper.new
  end

  # GET /shoppers/1/edit
  def edit
  end

  # POST /shoppers
  # POST /shoppers.json
  def create
    @shopper = Shopper.new(shopper_params)

    respond_to do |format|
      if @shopper.save
        format.html { redirect_to @shopper, notice: 'Shopper was successfully created.' }
        format.json { render :show, status: :created, location: @shopper }
      else
        format.html { render :new }
        format.json { render json: @shopper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shoppers/1
  # PATCH/PUT /shoppers/1.json
  def update
    respond_to do |format|
      if @shopper.update(shopper_params)
        format.html { redirect_to @shopper, notice: 'Shopper was successfully updated.' }
        format.json { render :show, status: :ok, location: @shopper }
      else
        format.html { render :edit }
        format.json { render json: @shopper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shoppers/1
  # DELETE /shoppers/1.json
  def destroy
    @shopper.destroy
    respond_to do |format|
      format.html { redirect_to shoppers_url, notice: 'Shopper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shopper
      @shopper = Shopper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shopper_params
      params.require(:shopper).permit(:name, :email, :nif)
    end
end

app/helpers/shoppers_helper.rb
module ShoppersHelper
end

app/views/shoppers/_form.html.erb
<%= form_with(model: shopper, local: true) do |form| %>
  <% if shopper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shopper.errors.count, "error") %> prohibited this shopper from being saved:</h2>

      <ul>
      <% shopper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :nif %>
    <%= form.text_field :nif %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shoppers/edit.html.erb
<h1>Editing Shopper</h1>

<%= render 'form', shopper: @shopper %>

<%= link_to 'Show', @shopper %> |
<%= link_to 'Back', shoppers_path %>

app/views/shoppers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shoppers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Nif</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shoppers.each do |shopper| %>
      <tr>
        <td><%= shopper.name %></td>
        <td><%= shopper.email %></td>
        <td><%= shopper.nif %></td>
        <td><%= link_to 'Show', shopper %></td>
        <td><%= link_to 'Edit', edit_shopper_path(shopper) %></td>
        <td><%= link_to 'Destroy', shopper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shopper', new_shopper_path %>

app/views/shoppers/new.html.erb
<h1>New Shopper</h1>

<%= render 'form', shopper: @shopper %>

<%= link_to 'Back', shoppers_path %>

app/views/shoppers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shopper.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @shopper.email %>
</p>

<p>
  <strong>Nif:</strong>
  <%= @shopper.nif %>
</p>

<%= link_to 'Edit', edit_shopper_path(@shopper) %> |
<%= link_to 'Back', shoppers_path %>