config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :shoppers
  resources :orders
  resources :merchants do
    resources :disbursements, only: :index
  end
  resources :disbursements, only: :index

  root 'merchants#index'
end

app/models/order.rb
class Order < ApplicationRecord
  SMALLER_THAN_50_FEE    = 0.01
  BETWEEN_50_AND_300_FEE = 0.0095
  OVER_300_FEE           = 0.0085

  scope :completed, -> { where.not(completed_at: [nil, '']) }

  belongs_to :merchant
  belongs_to :shopper

  validates :amount, presence: true
  validates :amount, numericality: { greater_than: 0 }

  def disbursement
    amount * (1 - disbursement_fee)
  end

  private

    def disbursement_fee
      case
      when amount < 50  then SMALLER_THAN_50_FEE
      when amount > 300 then OVER_300_FEE
      else
        BETWEEN_50_AND_300_FEE
      end
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:amount, :completed_at, :merchant_id, :shopper_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :completed_at %>
    <%= form.datetime_select :completed_at %>
  </div>

  <div class="field">
    <%= form.label :merchant_id %>
    <%= form.text_field :merchant_id %>
  </div>

  <div class="field">
    <%= form.label :shopper_id %>
    <%= form.text_field :shopper_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Completed at</th>
      <th>Merchant</th>
      <th>Shopper</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.amount %></td>
        <td><%= order.completed_at %></td>
        <td><%= order.merchant %></td>
        <td><%= order.shopper %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @order.amount %>
</p>

<p>
  <strong>Completed at:</strong>
  <%= @order.completed_at %>
</p>

<p>
  <strong>Merchant:</strong>
  <%= @order.merchant %>
</p>

<p>
  <strong>Shopper:</strong>
  <%= @order.shopper %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>