config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :shoppers
  resources :orders
  resources :merchants do
    resources :disbursements, only: :index
  end
  resources :disbursements, only: :index

  root 'merchants#index'
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  has_many :orders,        dependent: :destroy
  has_many :disbursements, dependent: :destroy

  validates :name, :email, :cif, presence: true
  validates :name, :email, length: { maximum: 120 }
  # TODO: add CustomValidator < ActiveModel::Validator for email and cif formats
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  before_action :set_merchant, only: [:show, :edit, :update, :destroy]

  # GET /merchants
  # GET /merchants.json
  def index
    @merchants = Merchant.all
  end

  # GET /merchants/1
  # GET /merchants/1.json
  def show
  end

  # GET /merchants/new
  def new
    @merchant = Merchant.new
  end

  # GET /merchants/1/edit
  def edit
  end

  # POST /merchants
  # POST /merchants.json
  def create
    @merchant = Merchant.new(merchant_params)

    respond_to do |format|
      if @merchant.save
        format.html { redirect_to @merchant, notice: 'Merchant was successfully created.' }
        format.json { render :show, status: :created, location: @merchant }
      else
        format.html { render :new }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /merchants/1
  # PATCH/PUT /merchants/1.json
  def update
    respond_to do |format|
      if @merchant.update(merchant_params)
        format.html { redirect_to @merchant, notice: 'Merchant was successfully updated.' }
        format.json { render :show, status: :ok, location: @merchant }
      else
        format.html { render :edit }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merchants/1
  # DELETE /merchants/1.json
  def destroy
    @merchant.destroy
    respond_to do |format|
      format.html { redirect_to merchants_url, notice: 'Merchant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_merchant
      @merchant = Merchant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def merchant_params
      params.require(:merchant).permit(:name, :email, :cif)
    end
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/views/merchants/_form.html.erb
<%= form_with(model: merchant, local: true) do |form| %>
  <% if merchant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(merchant.errors.count, "error") %> prohibited this merchant from being saved:</h2>

      <ul>
      <% merchant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :cif %>
    <%= form.text_field :cif %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/merchants/edit.html.erb
<h1>Editing Merchant</h1>

<%= render 'form', merchant: @merchant %>

<%= link_to 'Show', @merchant %> |
<%= link_to 'Back', merchants_path %>

app/views/merchants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Merchants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Cif</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @merchants.each do |merchant| %>
      <tr>
        <td><%= merchant.name %></td>
        <td><%= merchant.email %></td>
        <td><%= merchant.cif %></td>
        <td><%= link_to 'Show', merchant %></td>
        <td><%= link_to 'Edit', edit_merchant_path(merchant) %></td>
        <td><%= link_to 'Destroy', merchant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Merchant', new_merchant_path %>

app/views/merchants/new.html.erb
<h1>New Merchant</h1>

<%= render 'form', merchant: @merchant %>

<%= link_to 'Back', merchants_path %>

app/views/merchants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @merchant.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @merchant.email %>
</p>

<p>
  <strong>Cif:</strong>
  <%= @merchant.cif %>
</p>

<%= link_to 'Edit', edit_merchant_path(@merchant) %> |
<%= link_to 'Back', merchants_path %>