config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :shoppers
  resources :orders
  resources :merchants do
    resources :disbursements, only: :index
  end
  resources :disbursements, only: :index

  root 'merchants#index'
end

app/models/disbursement.rb
class Disbursement < ApplicationRecord
  belongs_to :merchant

  def self.calculate_by(merchant_id, orders, date)
    find_or_initialize_by(merchant_id: merchant_id, date: date).tap do |disbursement|
      disbursement.amount = orders.map(&:disbursement).sum
      disbursement.save!
    end
  end

  def self.week_total(date)
    from = date.beginning_of_week
    to   = date.end_of_week

    where(date: from..to).sum(:amount)
  end
end

app/controllers/disbursements_controller.rb
class DisbursementsController < ApplicationController
  before_action :set_end_of_week
  before_action :set_merchant

  def index
    if @merchant
      disbursement = @merchant.disbursements.find_by(date: @end_of_week)
      @amount = disbursement ? disbursement.amount : '0.00'
    else
      @amount = Disbursement.week_total(@end_of_week)
    end
  end

  private

    def set_end_of_week
      date = params[:date] ? Date.parse(params[:date]) : Date.today.prev_occurring(:sunday)
      @end_of_week = date.end_of_week
    end

    def set_merchant
      @merchant = Merchant.find(params[:merchant_id]) if params[:merchant_id]
    end
end

app/helpers/disbursements_helper.rb
module DisbursementsHelper
end

app/views/disbursements/_form.html.erb
<%= form_with(model: disbursement, local: true) do |form| %>
  <% if disbursement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(disbursement.errors.count, "error") %> prohibited this disbursement from being saved:</h2>

      <ul>
      <% disbursement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :merchant_id %>
    <%= form.text_field :merchant_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/disbursements/edit.html.erb
<h1>Editing Disbursement</h1>

<%= render 'form', disbursement: @disbursement %>

<%= link_to 'Show', @disbursement %> |
<%= link_to 'Back', disbursements_path %>

app/views/disbursements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Disbursements</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Date</th>
      <th>Merchant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @disbursements.each do |disbursement| %>
      <tr>
        <td><%= disbursement.amount %></td>
        <td><%= disbursement.date %></td>
        <td><%= disbursement.merchant %></td>
        <td><%= link_to 'Show', disbursement %></td>
        <td><%= link_to 'Edit', edit_disbursement_path(disbursement) %></td>
        <td><%= link_to 'Destroy', disbursement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Disbursement', new_disbursement_path %>

app/views/disbursements/new.html.erb
<h1>New Disbursement</h1>

<%= render 'form', disbursement: @disbursement %>

<%= link_to 'Back', disbursements_path %>

app/views/disbursements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @disbursement.amount %>
</p>

<p>
  <strong>Date:</strong>
  <%= @disbursement.date %>
</p>

<p>
  <strong>Merchant:</strong>
  <%= @disbursement.merchant %>
</p>

<%= link_to 'Edit', edit_disbursement_path(@disbursement) %> |
<%= link_to 'Back', disbursements_path %>